version: "3"
services:
    web:
        environment:
            - DEMO=1
            - MAX_UPLOAD=50 MB
            - POLL_INTERVAL=2000
            - WEB_CONCURRENCY=1
            # timeout: 1 day
            - JOB_TIMEOUT=86400
            # - SENTRY_URL=https://xx
            # - PRIVACY_URLS=https://example.com https://example.de

    rq_monitor:
        image: pd3f/rq-dashboard-3.8
        depends_on:
            - redis
        environment:
            - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
        ports:
            - "9181:9181"
        entrypoint:
            ["python3", "-m", "rq_dashboard", "--url-prefix", "/dashboard"]
