version: "3"
services:
    web:
        image: pd3f/pd3f:latest
        ports:
            - "1616:5000"
        depends_on:
            - redis
        volumes:
            - ./pd3f-data-uploads/:/uploads/
        command: gunicorn app:app --bind=0.0.0.0:5000

    parsr:
        image: axarev/parsr:v1.2.2
        expose:
            - 3001

    redis:
        image: redis:6-alpine
        expose:
            - 6379

    worker:
        image: pd3f/pd3f:latest
        depends_on:
            - parsr
            - redis
        volumes:
            - ./pd3f-data-uploads/:/uploads/
            - ./pd3f-data-to-ocr/:/to-ocr/
            - ./pd3f-data-cache/:/root/.cache/

        # delete results / files after one day
        environment:
            - KEEP_RESULTS_HOURS=24
        command: rq worker -u redis://redis:6379 --results-ttl 86400

    ocr_worker:
        image: pd3f/pd3f-ocr:latest
        volumes:
            - ./pd3f-data-to-ocr/:/to-ocr/
