version: "3"

volumes:
  cache:

services:
    web:
        image: pd3f/pd3f:latest
        ports:
            - "1616:5000"
        depends_on:
            - redis
            - parsr
            - worker
            - ocr_worker
        volumes:
            - ./data/pd3f-data-uploads/:/uploads/
        command: gunicorn app:app --bind=0.0.0.0:5000

    parsr:
        image: axarev/parsr:v1.2.2
        expose:
            - 3001

    redis:
        image: redis:6-alpine
        expose:
            - 6379

    worker:
        image: pd3f/pd3f:latest
        depends_on:
            - parsr
            - redis
        volumes:
            - cache:/root/.cache/
            - ./data/pd3f-data-uploads/:/uploads/
            - ./data/pd3f-data-to-ocr/:/to-ocr/

        # delete results / files after one day
        environment:
            - KEEP_RESULTS_HOURS=24
        command: rq worker -u redis://redis:6379 --results-ttl 86400

    ocr_worker:
        image: pd3f-ocr-worker
        build:
            context: ./pd3f-ocr
        volumes:
            - ./data/pd3f-data-to-ocr/:/to-ocr/
