version: "3"

services:
    web:
        build: .
        environment:
            - FLASK_ENV=development

        command: flask run --host 0.0.0.0
        volumes:
            - ./pd3f/:/app/
            - ./data/pd3f-data-uploads/:/uploads/
    worker:
        volumes:
            - ./pd3f/:/app/
            - to_ocr:/to-ocr/
            - ./data/pd3f-data-uploads/:/uploads/
