version: "3"

services:
    web:
        build: .
        environment:
            - FLASK_ENV=development
            - DEMO=1
            - MAX_UPLOAD=50 MB
            - PRIVACY_URLS=https://example.com https://example.de

        command: flask run --host 0.0.0.0
        volumes:
            - ./pd3f/:/app/
            - ./data/pd3f-data-uploads/:/uploads/
    worker:
        volumes:
            - ./pd3f/:/app/
            - ./data/pd3f-data-uploads/:/uploads/
            - ./data/pd3f-data-to-ocr/:/to-ocr/
